In [1]:
!pip install torch --break-system-packages

  Using cached torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (38 kB)
  Using cached setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)
  Using cached cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
  Using cached nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
  Using cached nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
  Using cached nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
  Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
  Using cached triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
  Using cached nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
  U

In [11]:
import torch
import torch.nn as nn

torch.manual_seed(42) #Pytorch own initializer, different starting point, different valley, different final numbers, same destination, different address

X = torch.tensor([[0.,0.], [0.,1.],[1.,0.], [1.,1.]])
y = torch.tensor([[0.], [1.], [1.], [0.]])

model = nn.Sequential(
    nn.Linear(2,2),  #W1, b1 (init included)
    nn.Sigmoid(),   # Our Sigmoid
    nn.Linear(2,1), #W2, b2
    nn.Sigmoid()
)

print(model[0].weight)

loss_fn = nn.MSELoss()      # np.mean((output - y)**2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5) #Our -==lr * lines

for epoch in range(10000):
    output = model(X)           # FORWARD
    loss = loss_fn(output, y)

    optimizer.zero_grad()   
    loss.backward()     #Our entire backward cell
    optimizer.step()    #the four weight updates

print(model(X).round(decimals=3))

Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496]], requires_grad=True)
tensor([[0.0390],
        [0.9650],
        [0.9650],
        [0.0360]], grad_fn=<RoundBackward1>)


In [3]:
model[0].weight

Parameter containing:
tensor([[4.1928, 4.1934],
        [5.8685, 5.8705]], requires_grad=True)

In [9]:
print(model[0].bias)

Parameter containing:
tensor([-6.4390, -2.5313], requires_grad=True)
